export interface Dua {
  id: string;
  title: string;
  category: string;
  arabic: string;
  transliteration: string;
  translation: string;
  source: string;
  when: string;
}

export interface DuaCategory {
  id: string;
  icon: string;
  label: string;
}

export const DUA_CATEGORIES: DuaCategory[] = [
  { id: "morning-evening", icon: "🌅", label: "Morning & Evening" },
  { id: "daily-life",      icon: "🙏", label: "Daily Life" },
  { id: "hardship",        icon: "😰", label: "Hardship & Relief" },
  { id: "worship",         icon: "🌙", label: "Worship" },
  { id: "gratitude",       icon: "🤲", label: "Gratitude & Praise" },
  { id: "protection",      icon: "🛡️", label: "Protection" },
  { id: "family",          icon: "👨‍👩‍👧", label: "Family & Relations" },
];

export const DUAS: Dua[] = [
  // ── Morning & Evening ──────────────────────────────────────────────────────
  {
    id: "morning-waking",
    title: "Dua Upon Waking",
    category: "morning-evening",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",
    translation: "All praise is for Allah who gave us life after having taken it from us and unto Him is the Resurrection.",
    source: "Bukhari 6312",
    when: "Immediately upon waking from sleep",
  },
  {
    id: "morning-adhkar",
    title: "Morning Remembrance",
    category: "morning-evening",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    transliteration: "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namutu wa ilaykan-nushur",
    translation: "O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is our resurrection.",
    source: "Tirmidhi 3391",
    when: "In the morning after Fajr",
  },
  {
    id: "evening-adhkar",
    title: "Evening Remembrance",
    category: "morning-evening",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    transliteration: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu wa ilaykal-masir",
    translation: "O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is our return.",
    source: "Tirmidhi 3391",
    when: "In the evening after Asr",
  },
  {
    id: "before-sleep",
    title: "Dua Before Sleep",
    category: "morning-evening",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amutu wa ahya",
    translation: "In Your name, O Allah, I die and I live.",
    source: "Bukhari 6324",
    when: "Just before going to sleep, while lying down",
  },
  {
    id: "ayat-kursi",
    title: "Ayat al-Kursi",
    category: "morning-evening",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
    transliteration: "Allahu la ilaha illa huwal-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ard...",
    translation: "Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth...",
    source: "Quran 2:255",
    when: "Morning and evening, and before sleep — provides protection throughout the day",
  },

  // ── Daily Life ─────────────────────────────────────────────────────────────
  {
    id: "before-eating",
    title: "Before Eating",
    category: "daily-life",
    arabic: "بِسْمِ اللَّهِ",
    transliteration: "Bismillah",
    translation: "In the name of Allah.",
    source: "Abu Dawud 3767",
    when: "Before starting any meal or drink",
  },
  {
    id: "after-eating",
    title: "After Eating",
    category: "daily-life",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transliteration: "Alhamdu lillahil-ladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation: "All praise is for Allah who fed me this and provided it for me without any might or power on my part.",
    source: "Tirmidhi 3458",
    when: "After finishing a meal",
  },
  {
    id: "entering-home",
    title: "Entering the Home",
    category: "daily-life",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Allahumma inni as'aluka khayral-mawliji wa khayral-makhraji, bismillahi walajna wa bismillahi kharajna wa 'alallahi rabbina tawakkalna",
    translation: "O Allah, I ask You for the blessing of entering and the blessing of leaving. In the name of Allah we enter, in the name of Allah we leave, and upon Allah our Lord we rely.",
    source: "Abu Dawud 5096",
    when: "Upon entering your home",
  },
  {
    id: "leaving-home",
    title: "Leaving the Home",
    category: "daily-life",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Bismillahi, tawakkaltu 'alallahi, wa la hawla wa la quwwata illa billah",
    translation: "In the name of Allah, I place my trust in Allah, and there is no might or power except with Allah.",
    source: "Tirmidhi 3426",
    when: "Upon leaving your home",
  },
  {
    id: "travel-dua",
    title: "Dua for Travel",
    category: "daily-life",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
    transliteration: "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun",
    translation: "Glory be to the One who has subjected this to us, and we could not have done it ourselves, and indeed to our Lord we shall return.",
    source: "Quran 43:13-14",
    when: "When boarding any vehicle or beginning a journey",
  },
  {
    id: "entering-masjid",
    title: "Entering the Masjid",
    category: "daily-life",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allahummaf-tah li abwaba rahmatik",
    translation: "O Allah, open for me the doors of Your mercy.",
    source: "Muslim 713",
    when: "Upon entering the masjid, stepping in with the right foot",
  },

  // ── Hardship & Relief ──────────────────────────────────────────────────────
  {
    id: "anxiety-relief",
    title: "Dua for Anxiety & Grief",
    category: "hardship",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-bukhli wal-jubn, wa dala'id-dayni wa ghalabatir-rijal",
    translation: "O Allah, I seek refuge in You from anxiety and grief, from incapacity and laziness, from miserliness and cowardice, from the burden of debt and the overpowering of men.",
    source: "Bukhari 6369",
    when: "When feeling anxious, worried, or overwhelmed",
  },
  {
    id: "debt-relief",
    title: "Dua for Relief from Debt",
    category: "hardship",
    arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    transliteration: "Allahumma-kfini bihalalika 'an haramika, wa aghnini bifadlika 'amman siwak",
    translation: "O Allah, suffice me with what You have made lawful against what You have made unlawful, and make me independent of all those besides You by Your bounty.",
    source: "Tirmidhi 3563",
    when: "When in financial difficulty or burdened by debt",
  },
  {
    id: "sayyid-istighfar",
    title: "Sayyid al-Istighfar",
    category: "hardship",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    transliteration: "Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayy, wa abu'u bidhanbi, faghfir li fa'innahu la yaghfirudh-dhunuba illa ant",
    translation: "O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant. I am following Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your blessing upon me, and I confess my sins to You, so forgive me, for none forgives sins except You.",
    source: "Bukhari 6306",
    when: "The master supplication for forgiveness — morning and evening, especially when repenting",
  },
  {
    id: "pain-relief",
    title: "Dua for Pain Relief",
    category: "hardship",
    arabic: "أَعُوذُ بِعِزَّةِ اللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ",
    transliteration: "A'udhu bi'izzatillahi wa qudratihi min sharri ma ajidu wa uhadhir",
    translation: "I seek refuge in the might of Allah and His power from the evil of what I am experiencing and what I fear.",
    source: "Muslim 2202",
    when: "When experiencing physical pain — place your hand on the pain and recite 7 times",
  },
  {
    id: "dua-qunoot",
    title: "Dua al-Qunoot",
    category: "hardship",
    arabic: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ",
    transliteration: "Allahumma-hdini fiman hadayt, wa 'afini fiman 'afayt, wa tawallani fiman tawallayt, wa barik li fima a'tayt",
    translation: "O Allah, guide me among those You have guided, pardon me among those You have pardoned, befriend me among those You have befriended, and bless me in what You have given.",
    source: "Abu Dawud 1425",
    when: "In the Witr prayer, during difficult times, and times of calamity",
  },

  // ── Worship ────────────────────────────────────────────────────────────────
  {
    id: "tahajjud-dua",
    title: "Dua for Tahajjud",
    category: "worship",
    arabic: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ نُورُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ أَنْتَ قَيِّمُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ",
    transliteration: "Allahumma lakal-hamd, anta nurus-samawati wal-ardi wa man fihinn, wa lakal-hamd, anta qayyimus-samawati wal-ardi wa man fihinn",
    translation: "O Allah, to You belongs all praise. You are the light of the heavens and the earth and all that is in them. To You belongs all praise. You are the Sustainer of the heavens and the earth and all that is in them.",
    source: "Bukhari 1120",
    when: "When rising for Tahajjud prayer in the last third of the night",
  },
  {
    id: "laylatul-qadr",
    title: "Dua for Laylatul Qadr",
    category: "worship",
    arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
    transliteration: "Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'anni",
    translation: "O Allah, You are the Pardoner and You love to pardon, so pardon me.",
    source: "Tirmidhi 3513",
    when: "During the last 10 nights of Ramadan, especially on odd nights",
  },
  {
    id: "after-salah",
    title: "Dua After Salah",
    category: "worship",
    arabic: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
    translation: "O Allah, help me to remember You, to thank You, and to worship You in the best manner.",
    source: "Abu Dawud 1522",
    when: "After every obligatory prayer",
  },
  {
    id: "breaking-fast",
    title: "Dua for Breaking Fast",
    category: "worship",
    arabic: "اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ",
    transliteration: "Allahumma laka sumtu wa 'ala rizqika aftartu",
    translation: "O Allah, for You I fasted and with Your provision I break my fast.",
    source: "Abu Dawud 2358",
    when: "At the time of breaking the fast during Ramadan",
  },
  {
    id: "istikhara",
    title: "Dua al-Istikhara",
    category: "worship",
    arabic: "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ وَتَعْلَمُ وَلَا أَعْلَمُ وَأَنْتَ عَلَّامُ الْغُيُوبِ",
    transliteration: "Allahumma inni astakhiruka bi'ilmika wa astaqdiruka biqudratika wa as'aluka min fadlikal-'azim, fa innaka taqdiru wa la aqdir, wa ta'lamu wa la a'lam, wa anta 'allamul-ghuyub",
    translation: "O Allah, I seek Your guidance through Your knowledge, and I seek Your assistance through Your power, and I ask You from Your great bounty. For You have power and I have none, You know and I do not, and You are the Knower of the unseen.",
    source: "Bukhari 1166",
    when: "When making an important decision — pray 2 rak'ahs then recite this dua",
  },

  // ── Gratitude & Praise ─────────────────────────────────────────────────────
  {
    id: "thanking-allah",
    title: "Thanking Allah",
    category: "gratitude",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ",
    transliteration: "Alhamdu lillahil-ladhi bini'matihi tatimmus-salihat",
    translation: "All praise is for Allah, through Whose blessings all good things are completed.",
    source: "Ibn Majah 3803",
    when: "When something good happens or when you want to express gratitude to Allah",
  },
  {
    id: "seeing-pleasing",
    title: "When Seeing Something Pleasing",
    category: "gratitude",
    arabic: "مَا شَاءَ اللَّهُ لَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Ma sha'Allahu la quwwata illa billah",
    translation: "Whatever Allah wills. There is no power except with Allah.",
    source: "Quran 18:39",
    when: "When you see something beautiful, admirable, or pleasing — protects from the evil eye",
  },
  {
    id: "subhanallah-tasbih",
    title: "After Salah Tasbih",
    category: "gratitude",
    arabic: "سُبْحَانَ اللَّهِ × ٣٣، الْحَمْدُ لِلَّهِ × ٣٣، اللَّهُ أَكْبَرُ × ٣٣",
    transliteration: "SubhanAllah x33, Alhamdulillah x33, Allahu Akbar x33",
    translation: "Glory be to Allah (33x), All praise is for Allah (33x), Allah is the Greatest (33x).",
    source: "Muslim 597",
    when: "After every obligatory prayer — expiates sins even if they are like the foam of the sea",
  },

  // ── Protection ─────────────────────────────────────────────────────────────
  {
    id: "three-quls",
    title: "Three Quls (Protection)",
    category: "protection",
    arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ... قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ... قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
    transliteration: "Qul Huwallahu ahad... Qul a'udhu birabbil-falaq... Qul a'udhu birabbin-nas",
    translation: "Recite Surah Al-Ikhlas, Al-Falaq, and An-Nas — the three surahs of seeking protection and affirming Tawhid.",
    source: "Abu Dawud 5082",
    when: "Morning and evening (3x each), and before sleep — comprehensive protection",
  },
  {
    id: "evil-eye-protection",
    title: "Protection from Evil Eye",
    category: "protection",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    source: "Muslim 2709",
    when: "Upon arriving at a new place, and as general protection throughout the day",
  },
  {
    id: "before-bathroom",
    title: "Entering the Bathroom",
    category: "protection",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
    transliteration: "Allahumma inni a'udhu bika minal-khubuthi wal-khaba'ith",
    translation: "O Allah, I seek refuge in You from the male and female evil beings.",
    source: "Bukhari 142",
    when: "Before entering the bathroom or toilet — recite in your heart",
  },

  // ── Family & Relations ─────────────────────────────────────────────────────
  {
    id: "dua-parents",
    title: "Dua for Parents",
    category: "family",
    arabic: "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transliteration: "Rabbir-hamhuma kama rabbayani saghira",
    translation: "My Lord, have mercy upon them as they brought me up when I was small.",
    source: "Quran 17:24",
    when: "After every prayer, especially for parents who have passed away",
  },
  {
    id: "dua-children",
    title: "Dua for Righteous Children",
    category: "family",
    arabic: "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ",
    transliteration: "Rabbi hab li minas-salihin",
    translation: "My Lord, grant me a child from among the righteous.",
    source: "Quran 37:100",
    when: "When supplicating for children — the dua of Ibrahim (AS)",
  },
  {
    id: "dua-spouse",
    title: "Dua for a Blessed Marriage",
    category: "family",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",
    translation: "Our Lord, grant us from among our wives and offspring comfort to our eyes and make us a leader for the righteous.",
    source: "Quran 25:74",
    when: "When seeking a spouse, or for blessings in your marriage and family",
  },
  {
    id: "visiting-sick",
    title: "Dua When Visiting the Sick",
    category: "family",
    arabic: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ، اشْفِهِ وَأَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
    transliteration: "Allahumma rabban-nasi adhhibil-ba's, ishfihi wa antash-shafi, la shifa'a illa shifa'uk, shifa'an la yughadiru saqama",
    translation: "O Allah, Lord of mankind, remove the harm and cure him. You are the Healer. There is no cure except Your cure — a cure that leaves no sickness.",
    source: "Bukhari 5675",
    when: "When visiting someone who is ill — recite 7 times and wipe over them if possible",
  },
];
